# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Passbolt Help
email: help@passbolt.com
description: > # this means to ignore newlines until "baseurl:"
 Need help? Passbolt has your back. Welcome to our knowledge base.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://passbolt.com" # the base hostname & protocol for your site
twitter_username: passbolt
github_username:  laurahilliger

# Build settings
markdown: kramdown
