---
title: Passbolt Help
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
<<<<<<< HEAD
  uploads:
    title: Uploads
    output: true
email: help@passbolt.com
description: 'Need help? Passbolt has your back. Welcome to our knowledge base.'
=======
  sets:
    title: Sets
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
- scope:
    path: ''
    type: sets
  values:
    _hide_content: true
- scope:
    path: index.html
  values:
    body_class: show_hero_search
email: help@passbolt.com
description: Knowledge base template for Jekyll.
baseurl: ''
url: http://passbolt.com
twitter_username: passbolt
github_username: laurahilliger
markdown: kramdown
logo: "/siteicon.png"
author:
  name: 
  email: 
  twitter: 
social:
  name: Base Template
  links:
  - https://github.com/CloudCannon/base-jekyll-template
permalink: "/:categories/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Google Plus
- Instagram
- LinkedIn
- Pinterest
- Tumblr
- Twitter
- YouTube
- Email
- RSS
types:
- Document
- Video
_comments: 
