---
title: Passbolt Help
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: help@passbolt.com
description: 'Need help? Passbolt has your back. Welcome to our knowledge base.

'
baseurl: ''
url: http://passbolt.com
twitter_username: passbolt
github_username: laurahilliger
markdown: kramdown
